- platform: rest
  resource: http://192.168.1.21:88/api/dimmer
  name: LR Spots Rear Level
  value_template: "{{ value }}"
  
- platform: rest
  resource: http://192.168.1.21:89/api/dimmer
  name: LR Spots Front Level
  value_template: "{{ value }}"
  
