title: Home
views:
  - path: home
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: sensor.energy_usage
        name: Load
      - entity: sensor.energy_consumed
        name: Consumed
      - entity: sensor.energy_budget
        name: Budget
      - entity: sensor.dining_room_sensor_temperature
        name: Temp
      - entity: sensor.dining_room_sensor_light_level
        name: Lux
      - entity: sun.sun
      - entity: sensor.yr_symbol
        name: weather
    cards:
      - type: entities
        entities:
          - group.theater_room
          - group.dining_room
          - group.lr_spots
          - switch.my_smart_plug
        title: Living Room
        show_header_toggle: true
      - type: entities
        entities:
          - group.bed_room
          - group.guest_room
        title: Bedrooms
        show_header_toggle: true
  
  - path: living
    title: Living Room
    theme: dark-mode
    badges:
      - entity: sensor.lr_spots_front_level
        name: Front Spots
      - entity: sensor.lr_spots_rear_level
        name: Rear Spots
      - entity: sensor.dining_room_sensor_temperature
        name: Temp
      - entity: sensor.dining_room_sensor_light_level
        name: Lux        
    cards:        
      - type: entities
        entities:
          - entity: light.lr_spots_front
            name: Front
          - entity: light.lr_spots_rear
            name: Rear
        title: LR Spots
        show_header_toggle: true    
      - type: entities
        entities:
          - light.lr_cove
          - light.lr_curtain
          - light.sofa_light
          - light.accent_strip
        title: Theater Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.dining_overhead
          - light.dining_lamp
        title: Dining Room
        show_header_toggle: true
      - type: entities
        entities:
          - script.cozy
          - script.normal
          - script.theater
        title: Scenes
      - type: media-control
        entity: media_player.shield_2
      - type: media-control
        entity: media_player.samsung_led65_ua65hu8500

  - path: bed
    title: Bed Rooms
    theme: dark-mode
    cards:
      - type: entities
        entities:
          - light.bedroom_cove
          - light.candle
        title: Bed Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.fan
          - light.diya
        title: Guest Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.bedroom
          - light.bedroom_cove_2
          - light.guest_room
          - light.living_dining
          - light.guest_room_2
        title: light


