- platform: rest
  resource: http://192.168.1.21:8070/api/dimmer/1
  name: LR Spots Rear Level
  value_template: "{{ value }}"
  
- platform: rest
  resource: http://192.168.1.21:8070/api/dimmer/2
  name: LR Spots Front Level
  value_template: "{{ value }}"
  
