- platform: unifi_status
  host: unifi.app.apandey.com
  port: 443
  verify_ssl: true
  username: !secret unifi_user
  password: !secret unifi_pass
  monitored_conditions:
    - firmware
    # - www
    # - wlan
    # - alerts
