lr_spots_front_set_brightness:
  url: http://192.168.1.21:8070/api/dimmer/2
  method: post
  payload: "{{ brightness }}"

lr_spots_rear_set_brightness:
  url: http://192.168.1.21:8070/api/dimmer/1
  method: post
  payload: "{{ brightness }}"

