homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  country: !secret country
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Hong_Kong
  # Customize 
  customize: !include_dir_merge_named extras/customize/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.1

# Show links to resources in log and frontend
# introduction:

system_health:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  # themes: !include_dir_merge_named extras/themes/

# manage frontend in code
lovelace: !include extras/lovelace.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

intent_script: !include_dir_merge_named extras/intent_scripts/

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

automation: !include automations.yaml
script: !include_dir_merge_named extras/scripts/
group: !include_dir_merge_named extras/groups/
emulated_hue: !include extras/emulated_hue.yaml
rest_command: !include_dir_merge_named extras/rest_commands/
sensor: !include_dir_merge_list extras/sensors/
# switch: !include_dir_merge_list extras/switches/
light: !include_dir_merge_list extras/lights/
mqtt: !include_dir_merge_list extras/mqtt/
# tplink: !include extras/tplink.yaml

# smartir:
#   check_updates: false

# climate:
#   - platform: smartir
#     name: Bedroom AC
#     unique_id: bedroom_ac
#     device_code: 9001
#     controller_data: remote.br_rm4_remote
#     temperature_sensor: sensor.br_rm4_temperature
#     humidity_sensor: sensor.br_rm4_humidity
#   power_sensor: binary_sensor.ac_power 

# climate:
#   - platform: generic_thermostat
#     name: my_cooler
#     unique_id: my_cooler
#     heater: switch.cooler_power
#     ac_mode: true
#     target_sensor: sensor.cooler_temperature
#     precision: 1.0
#     min_temp: 18
#     max_temp: 30
#     target_temp: 20
    # initial_hvac_mode: "off"
