title: Home
resources:
  - url: /local/plugins/slider-entity-row.js?v=20201220
    type: module
  - url: /local/plugins/fan-control-entity-row.js?v=20201220
    type: module
views:
  - path: home
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: sensor.energy_usage
        name: Load
      - entity: sensor.energy_consumed
        name: Consumed
      - entity: sensor.energy_budget
        name: Budget
      - entity: sensor.dining_room_sensor_temperature
        name: Temp
      - entity: sensor.dining_room_sensor_light_level
        name: Lux
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - group.theater_room
          - group.dining_room
          - group.lr_spots
          - switch.my_smart_plug
        title: Living Room
        show_header_toggle: true
      - type: entities
        entities:
          - group.bed_room
          - group.guest_room
        title: Bedrooms
        show_header_toggle: true
  
  - path: living
    title: Living Room
    theme: dark-mode
    badges:
      - entity: sensor.lr_spots_front_level
        name: Front Spots
      - entity: sensor.lr_spots_rear_level
        name: Rear Spots
      - entity: sensor.dining_room_sensor_temperature
        name: Temp
      - entity: sensor.dining_room_sensor_light_level
        name: Lux        
    cards:        
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.lr_spots_front
            name: Front
            step: 10
            toggle: true
          - type: custom:slider-entity-row
            entity: light.lr_spots_rear
            name: Rear
            step: 10
            toggle: true
        title: LR Spots
        show_header_toggle: true    
      - type: entities
        entities:
          - light.lr_cove
          - light.lr_curtain_strip
          - light.sofa_light
          - light.accent_strip
        title: Theater Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.dining_overhead
          - light.dining_lamp
        title: Dining Room
        show_header_toggle: true
      - type: entities
        entities:
          - script.cozy
          - script.normal
          - script.theater
        title: Scenes

  - path: bed
    title: Bed Rooms
    theme: dark-mode
    cards:
      - type: entities
        entities:
          - light.bedroom_cove
          - light.candle
          - entity: fan.bedroom_fan
            type: custom:fan-control-entity-row
        title: Bed Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.fan
          - light.diya
        title: Guest Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.bedroom
          - light.bedroom_cove_2
          - light.guest_room
          - light.living_dining
        title: light
