title: Home
resources:
  - url: /local/plugins/slider-entity-row.js?v=20201220
    type: module
  - url: /hacsfiles/fan-mode-button-row/fan-mode-button-row.js?v=20230902
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js?v=20230922
    type: module
views:
  - path: home
    title: Home
    badges:
      - entity: sensor.dining_room_sensor_battery
      - entity: sensor.bed_switch_battery
      - entity: sensor.bedroom_main_switch_battery
      - entity: sensor.bedroom_spare_switch_battery
      - entity: sensor.corridor_switch_battery
      - entity: sensor.dining_room_switch_battery
      - entity: sensor.guest_room_switch_battery
      - entity: sensor.dining_room_sensor_temperature
        name: LR Temp
      - entity: sensor.dining_room_sensor_illuminance
        name: Lux
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - group.theater_room
          - group.dining_room
          - group.lr_spots
          # - switch.my_smart_plug
        title: Living Room
        show_header_toggle: true
      - type: entities
        entities:
          - group.bed_room
          - group.guest_room
        title: Bedrooms
        show_header_toggle: true
  
  - path: living
    title: Living Room
    theme: dark-mode
    badges:
      - entity: sensor.lr_spots_front_level
        name: Front Spots
      - entity: sensor.lr_spots_rear_level
        name: Rear Spots
      - entity: sensor.dining_room_sensor_temperature
        name: Temp
      - entity: sensor.dining_room_sensor_light_level
        name: Lux        
    cards:        
      - type: entities
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.lr_spots_front
            name: Front
            step: 10
            toggle: true
          - type: 'custom:slider-entity-row'
            entity: light.lr_spots_rear
            name: Rear
            step: 10
            toggle: true
        title: LR Spots
        show_header_toggle: true    
      - type: entities
        entities:
          - light.lr_cove
          - light.lr_curtain_strip
          - light.sofa_light
          - light.accent_strip
        title: Theater Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.dining_overhead
          - light.dining_lamp
        title: Dining Room
        show_header_toggle: true
      - type: entities
        entities:
          - script.cozy
          - script.normal
          - script.theater
        title: Scenes

  - path: bed
    title: Bed Rooms
    theme: dark-mode
    cards:
      - type: entities
        entities:
          - entity: light.bedroom_cove
          - entity: light.candle
          - entity: fan.bedroom_fan
            type: 'custom:fan-mode-button-row'
        title: Bed Room
        show_header_toggle: true
      - type: custom:simple-thermostat
        entity: climate.my_cooler
        step_size: 1
        decimals: 0
        sensors:
          - name: Humidity
            entity: sensor.cooler_humidity
            decimals: 0
          - name: Temperature
            entity: sensor.cooler_temperature
            decimals: 0
        layout:
          step: column
          mode:
            names: true
            icons: true
            headings: false
        header: 
          name: Bedroom AC
          faults:
            - entity: binary_sensor.cooler_status
        control:
          hvac:
            _name: Mode
          fan:
            _name: Fan Mode
            "powerful":
              name: High
              icon: fan
          swing:
            _name: Swing Mode
          preset:
            _name: Preset Mode
      - type: entities
        entities:
          - light.guest_room_fan
          - light.diya
        title: Guest Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.bedroom
          - light.guest_room
        title: light
