- name: Guest Room Fan
  platform: group
  unique_id: guest_room_fan
  entities:
  - light.fan_1
  - light.fan_2
  - light.fan_3
- name: Living Room Spots
  platform: group
  unique_id: lr_spots
  entities:
  - light.lr_spots_front_2
  - light.lr_spots_rear_2
