- platform: mqtt  
  name: "Bedroom Fan"
  command_topic: "cmnd/tasmota_br_fan/FanSpeed"
  speed_command_topic: "cmnd/tasmota_br_fan/FanSpeed"    
  state_topic: "stat/tasmota_br_fan/RESULT"
  speed_state_topic: "stat/tasmota_br_fan/RESULT"
  state_value_template: >
    {% if value_json.FanSpeed is defined %}
      {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
    {% else %}
      {% if states.fan.bedroom_fan.state == 'off' -%}0{%- elif states.fan.bedroom_fan.state == 'on' -%}4{%- endif %}
    {% endif %}
  speed_value_template: "{{ value_json.FanSpeed }}"
  availability_topic: tele/tasmota_br_fan/LWT
  payload_off: "0"
  payload_on: "4"
  payload_low_speed: "1"
  payload_medium_speed: "2"
  payload_high_speed: "3"
  payload_available: Online
  payload_not_available: Offline
  speeds:
    - off
  