lr_spots:
  name: LR Spots
  entities:
  - light.lr_spots_front
  - light.lr_spots_rear
theater_room:
  name: Theater Room
  entities:
  - light.lr_cove
  - light.lr_curtain_strip
  - light.sofa_light
  - light.accent_strip
dining_room:
  name: Dining Room
  entities:
  - light.dining_overhead
  - light.dining_lamp
living_room:
  name: Living Room
  entities:
  - group.theater_room
  - group.dining_room
  - group.lr_spots
  # - switch.my_smart_plug
bed_room:
  name: Bed Room
  entities:
  - light.bedroom_cove
  - light.candle
guest_room:
  name: Guest Room
  entities:
  - light.guest_room_fan
  - light.diya 
