listen_port: 8300
# host_ip: 192.168.1.215
upnp_bind_multicast: False
advertise_ip: 192.168.1.28
advertise_port: 80
expose_by_default: false
off_maps_to_on_domains:
  - scene
  - script
entities:
  light.lr_spots:
    name: Living Room Spots
    hidden: false
  switch.my_smart_plug:
    name: Christmas Light
    hidden: false
  light.lr_spots_front:
    name: Front Spots
    hidden: false
  light.lr_spots_rear:
    name: Rear Spots
    hidden: false
  # script.normal:
  #   name: Normal Lights
  #   hidden: false
  # script.cozy:
  #   name: Cozy Lights
  #   hidden: false
  # script.theater:
  #   name: Theater Lights
  #   hidden: false
